### PR TITLE
Login page is finished

### LINKED ISSUE #2: Login Page

### PR DESCRIPTION
**Pull request by Thanabardi**
The login page is now complete and ready to merge. Also, I fixed bugs on the color template in `tailwind.config.js`.

### CODE REVIEW

**Comment by patkamon** [comment]
well done na Mr. [Thanabardi](https://github.com/Thanabardi)

**Review by patkamon — APPROVED** [review]
excellent well done na Mr. [Thanabardi](https://github.com/Thanabardi)

**Review by touchtool — APPROVED** [review]
The login page is looking good. :octocat:

**Review by Ditthapeem — APPROVED** [review]
The login page is looking good for me, good job.

**Review by natchanon-space — APPROVED** [review]

**Pull request merged**
