### PR TITLE
All pages have been combined and ready to merge

### LINKED ISSUE #6: Combine All Pages

### LINKED ISSUE #12: Combine All Page

### PR DESCRIPTION
**Pull request by Thanabardi**
The first version of the web page is finished.

### CODE REVIEW

**Review by patkamon — APPROVED** [review]
optional fix:
 home page did not fit screen it can be scroll?
 path should be - over _ ie. `/party-list`, `/vote-candidate/`

**Comment by Thanabardi** [comment]
I believe that your resolution is set to 125%, because at 100% everything looks fine. And yes, the page is scroll-able if the content is overflow.

**Review by touchtool — APPROVED** [review]
Everything is looking good now. 👍

**Review by Ditthapeem — APPROVED** [review]
Every page looks good.

**Pull request merged**
